// RENO APARTMENTS ABUJA — GALLERY MANIFEST
// Auto-generated list of the property's own photography, grouped by category.
const GALLERY = [
  { file: "images/gallery/exterior-1.jpg", category: "exterior", label: "Property Entrance at Night" },
  { file: "images/gallery/exterior-2.jpg", category: "exterior", label: "Building Exterior - Daytime" },
  { file: "images/gallery/exterior-3.jpg", category: "exterior", label: "Entrance Doors" },
  { file: "images/gallery/exterior-4.jpg", category: "exterior", label: "Building Exterior" },
  { file: "images/gallery/exterior-5.jpg", category: "exterior", label: "Reno Signage Entrance" },
  { file: "images/gallery/exterior-6.jpg", category: "exterior", label: "Street View" },
  { file: "images/gallery/exterior-7.jpg", category: "exterior", label: "Building at Night" },
  { file: "images/gallery/exterior-8.jpg", category: "exterior", label: "Building Facade" },
  { file: "images/gallery/exterior-9.jpg", category: "exterior", label: "Compound Gate" },
  { file: "images/gallery/exterior-10.jpg", category: "exterior", label: "Building - Night View" },
  { file: "images/gallery/exterior-11.jpg", category: "exterior", label: "Building - Daytime" },
  { file: "images/gallery/lobby-1.jpg", category: "lobby", label: "Lobby - Marble Floor Detail" },
  { file: "images/gallery/lobby-2.jpg", category: "lobby", label: "Reception Lounge" },
  { file: "images/gallery/lobby-3.jpg", category: "lobby", label: "Lounge Seating Area" },
  { file: "images/gallery/lobby-4.jpg", category: "lobby", label: "Lobby Seating" },
  { file: "images/gallery/lobby-5.jpg", category: "lobby", label: "Lounge Area" },
  { file: "images/gallery/lobby-6.jpg", category: "lobby", label: "Lounge Seating" },
  { file: "images/gallery/lobby-7.jpg", category: "lobby", label: "Lounge Chairs" },
  { file: "images/gallery/lobby-8.jpg", category: "lobby", label: "Lobby Marble Detail" },
  { file: "images/gallery/lobby-9.jpg", category: "lobby", label: "Reception Desk Area" },
  { file: "images/gallery/bedroom-1.jpg", category: "bedroom", label: "Guest Room" },
  { file: "images/gallery/bedroom-2.jpg", category: "bedroom", label: "Guest Room - White & Gold" },
  { file: "images/gallery/bedroom-3.jpg", category: "bedroom", label: "Guest Room - Warm Tones" },
  { file: "images/gallery/bedroom-4.jpg", category: "bedroom", label: "Guest Room - Black Headboard" },
  { file: "images/gallery/bedroom-5.jpg", category: "bedroom", label: "Guest Room - Purple Accents" },
  { file: "images/gallery/bedroom-6.jpg", category: "bedroom", label: "Guest Room Ceiling Detail" },
  { file: "images/gallery/bedroom-7.jpg", category: "bedroom", label: "Guest Room" },
  { file: "images/gallery/bedroom-8.jpg", category: "bedroom", label: "Guest Room with Glass Door" },
  { file: "images/gallery/bedroom-9.jpg", category: "bedroom", label: "Guest Room" },
  { file: "images/gallery/bedroom-10.jpg", category: "bedroom", label: "Guest Room - TV & Seating" },
  { file: "images/gallery/bedroom-11.jpg", category: "bedroom", label: "Guest Room with TV" },
  { file: "images/gallery/bathroom-1.jpg", category: "bathroom", label: "Bathroom - Glass Shower" },
  { file: "images/gallery/bathroom-2.jpg", category: "bathroom", label: "Bathroom - Marble Mirror" },
  { file: "images/gallery/bathroom-3.jpg", category: "bathroom", label: "Bathroom - Glass Shower" },
  { file: "images/gallery/bathroom-4.jpg", category: "bathroom", label: "Bathroom - Glass Shower" },
  { file: "images/gallery/bathroom-5.jpg", category: "bathroom", label: "Bathroom - Glass Door" },
  { file: "images/gallery/bathroom-6.jpg", category: "bathroom", label: "Bathroom - Marble Finish" },
  { file: "images/gallery/bathroom-7.jpg", category: "bathroom", label: "Bathroom" },
  { file: "images/gallery/bathroom-8.jpg", category: "bathroom", label: "Bathroom Sink Detail" },
  { file: "images/gallery/bathroom-9.jpg", category: "bathroom", label: "Bathroom" },
  { file: "images/gallery/dining-1.jpg", category: "dining", label: "In-Room Dining" },
  { file: "images/gallery/dining-2.jpg", category: "dining", label: "Dining Spread" },
  { file: "images/gallery/dining-3.jpg", category: "dining", label: "Dining Experience" },
  { file: "images/gallery/dining-4.jpg", category: "dining", label: "Dining Area" },
  { file: "images/gallery/dining-5.jpg", category: "dining", label: "Dining Service" },
  { file: "images/gallery/dining-6.jpg", category: "dining", label: "Dining Spread" },
  { file: "images/gallery/dining-7.jpg", category: "dining", label: "Dining Spread" },
  { file: "images/gallery/dining-8.jpg", category: "dining", label: "Dining Spread" },
  { file: "images/gallery/dining-9.jpg", category: "dining", label: "Dining Hall" },
  { file: "images/gallery/dining-10.jpg", category: "dining", label: "Kitchenette" },
  { file: "images/gallery/dining-11.jpg", category: "dining", label: "Dining Area" },
  { file: "images/gallery/amenities-1.jpg", category: "amenities", label: "Games Room - Pool Table" },
  { file: "images/gallery/amenities-2.jpg", category: "amenities", label: "Guest Corridor" },
  { file: "images/gallery/amenities-3.jpg", category: "amenities", label: "Elevator" },
  { file: "images/gallery/amenities-4.jpg", category: "amenities", label: "Laundry Facility" },
  { file: "images/gallery/amenities-5.jpg", category: "amenities", label: "Outdoor Seating" },
  { file: "images/gallery/amenities-6.jpg", category: "amenities", label: "Corridor" },
  { file: "images/gallery/amenities-7.jpg", category: "amenities", label: "Outdoor Patio" },
  { file: "images/gallery/amenities-8.jpg", category: "amenities", label: "Guest Corridor" },
  { file: "images/gallery/amenities-9.jpg", category: "amenities", label: "Laundry Facility" },
  { file: "images/gallery/amenities-10.jpg", category: "amenities", label: "Elevator" },
  { file: "images/gallery/amenities-11.jpg", category: "amenities", label: "Mini Bar / Pantry" },
];
// Top-level `const` does not become a `window` property automatically —
// this explicit assignment makes `window.GALLERY` available to other scripts.
window.GALLERY = GALLERY;
if (typeof module !== 'undefined') { module.exports = GALLERY; }
